In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os


In [3]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
data=pd.read_csv('/kaggle/input/avocado-prices/avocado.csv')
data.head(5)

/kaggle/input/avocado-prices/avocado.csv


Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0           0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1           1  2015-12-20          1.35      54876.98   674.28   44638.81   
2           2  2015-12-13          0.93     118220.22   794.70  109149.67   
3           3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4           4  2015-11-29          1.28      51039.60   941.48   43838.39   

     4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0   48.16     8696.87     8603.62       93.25          0.0  conventional   
1   58.33     9505.56     9408.07       97.49          0.0  conventional   
2  130.50     8145.35     8042.21      103.14          0.0  conventional   
3   72.58     5811.16     5677.40      133.76          0.0  conventional   
4   75.78     6183.95     5986.26      197.69          0.0  conventional   

   year  region  
0  2015  Albany  
1  2015  Albany  
2  2015  Albany  
3  2015  Albany  
4  2015  Albany

In [ ]:
#data=pd.read_csv("avocado.csv")
#data.head(5)

In [4]:
df=data[["year","Small Bags","Large Bags", "AveragePrice"]]

df = df.sample(n=50,replace=True)
#df=df.head(50)
df.tail()

year  Small Bags  Large Bags  AveragePrice
1521   2015   589490.48    93363.67          1.13
13921  2016     2195.03      204.94          1.79
10265  2015      383.33        0.00          1.60
6395   2017    39418.90     6580.28          1.67
11269  2015      491.27        0.00          1.82

In [ ]:
df.dtypes

In [ ]:
df.isna().sum()

## Prediction for SMALL BAGS & The average price

In [5]:
y=df.iloc[:,1].values
x=df.iloc[:,-1].values

In [7]:
x=x.reshape(len(x),1)
y=y.reshape(len(y),1)


## Training the Decision Tree Regression model on the whole dataset

In [13]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100, random_state=0)
regressor.fit(x,y)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(random_state=0)

In [14]:
## Predicting a new result: What is the price for the 
regressor.predict([[8042.21]])


array([9778.593])

In [15]:
regressor.predict([[8000]])


array([9778.593])

In [17]:
regressor.predict([[2]])


array([9778.593])

## Visualization

In [ ]:
X_grid = np.arange(min(x), max(x), 0.001)
X_grid = X_grid.reshape((len(X_grid), 1))

plt.scatter(x,y, color="red")
plt.plot(X_grid, regressor.predict(X_grid), color="blue")

plt.title("Decision Tree Regression for Avocado Prices")
plt.xlabel("Avocado Small Bags")
plt.ylabel("Price")
plt.show()
